### PR TITLE
added the technology inclusivity language guidebook

### PR DESCRIPTION
**Pull request by xebitstudios**
This document is for a page that displays Accenture's technology inclusivity guide.

### CODE REVIEW

**Comment by oscarrenalias** [comment]
Apologies for the delay, I totally forgot about this.

Before we merge the PR, is it related to the work that Ned Visolyaputra was doing a while ago about this topic, or something you're contributing on your own?

**Comment by oscarrenalias** [comment]
I checked internally with Ned and he confirmed that this is the same thing, I have just merged the PR.

However, this is currently created as a draft blog page. Wouldn't it better if it's a a top-level static page? So that'd be at the same level as "about", "blog", "conferences", etc, so that it's visible and more easily referenceable?

**Comment by xebitstudios** [comment]
@oscarrenalias What do i need to do to have this show up on the top-level on say "/accesibility" path? 

Are there instructions somwhere to follow?

**Comment by oscarrenalias** [comment]
The site is built on Jenkins, so Jenkins instructions can be followed.

Nevertheless, it's very straightforward, see how some of our existing top-level pages do it:

1) create a markdown file at the root of the repo with your content, e.g. inclusivity.md and point it to a layout called "inclusivity". Example: https://github.com/Accenture/accenture.github.io/blob/master/kubernetes.md

2) create a layout under _layouts/, call it "inclusivity.html" (or whatever you want, but it needs to be the same as in the .md file above), and add your Markdown content in there. Example: https://github.com/Accenture/accenture.github.io/blob/master/_layouts/kubernetes.html

I can't remember right now, but I think the top-level nav bar should update automatically and include your new page.

**Pull request merged**
